### ISSUE TITLE
Update repo to 0.8.0

### ISSUE THREAD

**Issue by jbaxleyiii** [peerlibrary/meteor-base-component#2]
Would it be possible to push the 0.8.0 update to github? We use base-component in our app and I would love to update.

https://github.com/peerlibrary/meteor-blaze-components/blob/master/package.js#L25

**Comment by mitar** [comment]
Oh. My mistake. Forgot to push. Thanks for noticing and reporting.

Just curious, how are you using base in your app?

I am using it for something like shadow components. Components you want in the component hierarchy, but not really rendered.
